// Code Generated by Sidekick is for learning and experimentation purposes only.

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    // Add cssnano for production CSS optimization (optional)
    ...(process.env.NODE_ENV === 'production' ? { cssnano: {} } : {})
  },
}
