// Code Generated by Sidekick is for learning and experimentation purposes only.

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  
  theme: {
    extend: {
      colors: {
        // ✅ Use CSS variables for dynamic theming (set by backend via embed.ts)
        'theme': {
          primary: 'var(--color-theme-primary, #2563EB)',
          'primary-hover': 'var(--color-theme-primary-hover, #1d4ed8)',
          'primary-light': 'var(--color-theme-primary-light, #dbeafe)',
          secondary: 'var(--color-theme-secondary, #1d4ed8)',
        },
        // ✅ Contrast text colors that dynamically adjust based on background brightness
        'text': {
          'on-primary': 'var(--color-text-on-primary, #ffffff)',
          'on-secondary': 'var(--color-text-on-secondary, #1f2937)',
        },
      },
      
      // Widget-specific z-index
      zIndex: {
        'widget': '999999',
        'widget-window': '999998',
      },
      
      // Consistent shadows for widget
      boxShadow: {
        'widget': '0 4px 12px rgba(0, 0, 0, 0.15)',
        'widget-lg': '0 10px 25px rgba(0, 0, 0, 0.2)',
        'widget-xl': '0 8px 24px rgba(0, 0, 0, 0.15), 0 4px 8px rgba(0, 0, 0, 0.1)',
      },
      
      // Widget-specific border radius
      borderRadius: {
        'widget': '12px',
      },
      
      // ✅ Add custom animations
      animation: {
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      
      keyframes: {
        slideUp: {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          'from': { opacity: '0', transform: 'translateY(10px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  
  // ✅ Don't reset host page styles (important for widget embed)
  corePlugins: {
    preflight: false,
  },
  
  plugins: [],
  
  // ✅ Important: Don't purge widget classes in production
  safelist: [
    'bg-theme-primary',
    'bg-theme-primary-hover',
    'bg-theme-primary-light',
    'bg-theme-secondary',
    'text-theme-primary',
    'text-text-on-primary',
    'text-text-on-secondary',
    'border-theme-primary',
    'hover:bg-theme-primary-hover',
    'focus:ring-theme-primary-light',
  ],
}
