// Code Generated by Sidekick is for learning and experimentation purposes only.

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import svgr from 'vite-plugin-svgr'

export default defineConfig(({ mode }) => {
  const isDev = mode === 'development'
  
  return {
    plugins: [
      react(), 
      svgr()
    ],
    
    // Development server
    server: {
      port: 3000,
      open: true,
      cors: true,
      host: true,
    },
    
    // Build configuration
    build: {
      minify: isDev ? false : 'esbuild',
      sourcemap: isDev ? true : false,
      cssCodeSplit: false, // ✅ Keep CSS in separate file for auto-loading
      outDir: 'dist',
      emptyOutDir: true,
      
      rollupOptions: {
        input: {
          embed: resolve(__dirname, 'src/embed.ts'),
        },
        output: {
          format: 'iife',
          name: 'GreetoChatWidget',
          entryFileNames: 'widget.js',
          chunkFileNames: 'chunks/[name]-[hash].js',
          assetFileNames: (assetInfo) => {
            // ✅ Ensure CSS has predictable name for auto-loading
            if (assetInfo.name?.endsWith('.css')) {
              return 'widget.css';
            }
            return 'assets/[name]-[hash][extname]';
          },
          inlineDynamicImports: true,
          globals: {
            react: 'React',
            'react-dom': 'ReactDOM'
          }
        },
        external: [],
      },
      
      target: ['es2020', 'chrome87', 'safari14', 'firefox78', 'edge88'],
      reportCompressedSize: true,
      chunkSizeWarningLimit: 800,
      cssMinify: true,
      assetsInlineLimit: 4096,
    },
    
    // Module resolution
    resolve: {
      alias: {
        '@': resolve(__dirname, './src'),
      },
    },
    
    // Environment variables
    define: {
      'process.env.NODE_ENV': JSON.stringify(mode),
      '__DEV__': JSON.stringify(isDev),
    },
    
    // Optimize dependencies
    optimizeDeps: {
      include: ['react', 'react-dom', 'axios'],
      esbuildOptions: {
        target: 'es2020',
      },
    },
    
    // Enable ESBuild optimizations
    esbuild: {
      logOverride: { 'this-is-undefined-in-esm': 'silent' },
      legalComments: 'none',
      treeShaking: true,
    },
  }
})
