// Code Generated by Sidekick is for learning and experimentation purposes only.

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import svgr from 'vite-plugin-svgr'
import fs from 'fs'
import type { Plugin } from 'vite'

// ✅ Plugin to serve widget files from root on dev server
const serveWidgetFilesPlugin = (): Plugin => ({
  name: 'serve-widget-files',
  apply: 'serve',
  configureServer(server) {
    // Add middleware directly (not wrapped in return)
    server.middlewares.use((req, res, next) => {
      const url = req.url || '';
      
      // Check if requesting widget.js or widget.css
      if (url === '/widget.js' || url === '/widget.css' || url.startsWith('/widget.js?') || url.startsWith('/widget.css?')) {
        const pathname = url.split('?')[0];
        const filePath = resolve(__dirname, `dist${pathname}`);
        
        // Check if file exists in dist
        if (fs.existsSync(filePath)) {
          try {
            const content = fs.readFileSync(filePath);
            const isJs = pathname.endsWith('.js');
            const contentType = isJs ? 'application/javascript;charset=utf-8' : 'text/css;charset=utf-8';
            
            res.writeHead(200, {
              'Content-Type': contentType,
              'Content-Length': Buffer.byteLength(content),
              'Access-Control-Allow-Origin': '*',
              'Cache-Control': 'no-cache'
            });
            res.end(content);
            return; // Stop processing, don't call next()
          } catch (err) {
            console.error(`[serve-widget-files] Error reading ${pathname}:`, err);
            res.writeHead(500, { 'Content-Type': 'text/plain' });
            res.end('Internal Server Error');
            return;
          }
        } else {
          // File not found, but still prevent SPA fallback
          console.warn(`[serve-widget-files] File not found: ${filePath}`);
          res.writeHead(404, { 'Content-Type': 'text/plain' });
          res.end('Not Found');
          return;
        }
      }
      
      // Let other middleware/handlers process this request
      next();
    });
  }
});

export default defineConfig(({ mode }) => {
  const isDev = mode === 'development'
  const buildTarget = process.env.VITE_BUILD_TARGET || 'app'
  
  // Widget library build configuration
  if (buildTarget === 'widget') {
    return {
      plugins: [react(), svgr()],
      
      build: {
        lib: {
          entry: resolve(__dirname, 'src/embed.ts'),
          name: 'GreetoChatWidget',
          fileName: 'widget',
          formats: ['iife']
        },
        minify: isDev ? false : 'esbuild',
        sourcemap: isDev ? true : false,
        outDir: 'dist',
        emptyOutDir: false, // ✅ Don't empty dist since app build already ran
        
        rollupOptions: {
          output: {
            entryFileNames: 'widget.js',
            assetFileNames: (assetInfo) => {
              if (assetInfo.name?.endsWith('.css')) {
                return 'widget.css'
              }
              return '[name][extname]'
            },
            globals: {
              react: 'React',
              'react-dom': 'ReactDOM'
            }
          },
          external: []
        },
        
        target: ['es2020', 'chrome87', 'safari14', 'firefox78', 'edge88'],
        reportCompressedSize: true,
        cssMinify: true,
      },
      
      resolve: {
        alias: {
          '@': resolve(__dirname, './src'),
        },
      },
      
      define: {
        'process.env.NODE_ENV': JSON.stringify(mode),
        '__DEV__': JSON.stringify(isDev),
      },
      
      esbuild: {
        logOverride: { 'this-is-undefined-in-esm': 'silent' },
        legalComments: 'none',
        treeShaking: true,
      },
    }
  }
  
  // Default React app build configuration
  return {
    plugins: [
      react(), 
      svgr(),
      serveWidgetFilesPlugin()
    ],
    
    // Development server
    server: {
      port: 3000,
      open: true,
      cors: true,
      host: true,
    },
    
    // Build configuration
    build: {
      minify: isDev ? false : 'esbuild',
      sourcemap: isDev ? true : false,
      cssCodeSplit: false, // ✅ Keep CSS in separate file for auto-loading
      outDir: 'dist',
      emptyOutDir: true,
      
      rollupOptions: {
        external: [],
      },
      
      target: ['es2020', 'chrome87', 'safari14', 'firefox78', 'edge88'],
      reportCompressedSize: true,
      chunkSizeWarningLimit: 800,
      cssMinify: true,
      assetsInlineLimit: 4096,
    },
    
    // Module resolution
    resolve: {
      alias: {
        '@': resolve(__dirname, './src'),
      },
    },
    
    // Environment variables
    define: {
      'process.env.NODE_ENV': JSON.stringify(mode),
      '__DEV__': JSON.stringify(isDev),
    },
    
    // Optimize dependencies
    optimizeDeps: {
      include: ['react', 'react-dom', 'axios'],
      esbuildOptions: {
        target: 'es2020',
      },
    },
    
    // Enable ESBuild optimizations
    esbuild: {
      logOverride: { 'this-is-undefined-in-esm': 'silent' },
      legalComments: 'none',
      treeShaking: true,
    },
  }
})
