// Code Generated by Sidekick is for learning and experimentation purposes only.

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'
import svgr from 'vite-plugin-svgr'

export default defineConfig(({ mode }) => {
  const isDev = mode === 'development'
  const buildTarget = process.env.VITE_BUILD_TARGET || 'app'
  
  // Widget library build configuration
  if (buildTarget === 'widget') {
    return {
      plugins: [react(), svgr()],
      
      build: {
        lib: {
          entry: resolve(__dirname, 'src/embed.ts'),
          name: 'GreetoChatWidget',
          fileName: 'widget',
          formats: ['iife']
        },
        minify: isDev ? false : 'esbuild',
        sourcemap: isDev ? true : false,
        outDir: 'dist',
        emptyOutDir: false, // ✅ Don't empty dist since app build already ran
        
        rollupOptions: {
          output: {
            entryFileNames: 'widget.js',
            assetFileNames: (assetInfo) => {
              if (assetInfo.name?.endsWith('.css')) {
                return 'widget.css'
              }
              return '[name][extname]'
            },
            globals: {
              react: 'React',
              'react-dom': 'ReactDOM'
            }
          },
          external: []
        },
        
        target: ['es2020', 'chrome87', 'safari14', 'firefox78', 'edge88'],
        reportCompressedSize: true,
        cssMinify: true,
      },
      
      resolve: {
        alias: {
          '@': resolve(__dirname, './src'),
        },
      },
      
      define: {
        'process.env.NODE_ENV': JSON.stringify(mode),
        '__DEV__': JSON.stringify(isDev),
      },
      
      esbuild: {
        logOverride: { 'this-is-undefined-in-esm': 'silent' },
        legalComments: 'none',
        treeShaking: true,
      },
    }
  }
  
  // Default React app build configuration
  return {
    plugins: [
      react(), 
      svgr()
    ],
    
    // Development server
    server: {
      port: 3000,
      open: true,
      cors: true,
      host: true,
    },
    
    // Build configuration
    build: {
      minify: isDev ? false : 'esbuild',
      sourcemap: isDev ? true : false,
      cssCodeSplit: false, // ✅ Keep CSS in separate file for auto-loading
      outDir: 'dist',
      emptyOutDir: true,
      
      rollupOptions: {
        external: [],
      },
      
      target: ['es2020', 'chrome87', 'safari14', 'firefox78', 'edge88'],
      reportCompressedSize: true,
      chunkSizeWarningLimit: 800,
      cssMinify: true,
      assetsInlineLimit: 4096,
    },
    
    // Module resolution
    resolve: {
      alias: {
        '@': resolve(__dirname, './src'),
      },
    },
    
    // Environment variables
    define: {
      'process.env.NODE_ENV': JSON.stringify(mode),
      '__DEV__': JSON.stringify(isDev),
    },
    
    // Optimize dependencies
    optimizeDeps: {
      include: ['react', 'react-dom', 'axios'],
      esbuildOptions: {
        target: 'es2020',
      },
    },
    
    // Enable ESBuild optimizations
    esbuild: {
      logOverride: { 'this-is-undefined-in-esm': 'silent' },
      legalComments: 'none',
      treeShaking: true,
    },
  }
})
