// Code Generated by Sidekick is for learning and experimentation purposes only.

export interface Message {
  role: 'user' | 'assistant';
  content: string;
  sources?: Source[];  // ✅ Add sources to message
  needsHuman?: boolean; // ✅ Flag when bot can't answer
}

// ✅ Add Source interface to match your API response
export interface Source {
  url: string;
  similarity: number;
}

// ✅ Complete ChatResponse matching your actual API
export interface ChatResponse {
  response: string;
  conversationId: number;
  clientName: string;
  sources?: Source[];  // ✅ Sources from RAG
  contextsUsed?: number;  // ✅ How many chunks were used
  needsHuman?: boolean;  // ✅ Flag when bot can't answer the question
}

// ✅ Add conversation history type
export interface ConversationMessage {
  id: number;
  role: 'user' | 'assistant';
  content: string;
  created_at: string;
}

export interface ConversationHistoryResponse {
  conversationId: number;
  messages: ConversationMessage[];
}
