// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/types/lead.ts - Lead form types

export interface LeadSubmitRequest {
  visitorId: string;
  name: string;
  email: string;
  phone?: string;
  company?: string;
  conversationId?: number;
}

export interface Lead {
  id: string;
  visitor_id: string;
  name: string;
  email: string;
  phone?: string;
  company?: string;
  conversation_id?: number | null;
  created_at: string;
  updated_at: string;
}

export interface LeadSubmitResponse {
  success: boolean;
  leadId: string;
  isNew: boolean;
  lead: Lead;
}

export interface LeadFormData {
  name: string;
  email: string;
  phone: string;
  company: string;
}

export interface LeadFormErrors {
  name?: string;
  email?: string;
  phone?: string;
  company?: string;
}
