// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/types/window.d.ts

export interface WidgetConfig {
  primaryColor: string;
  secondaryColor: string;
  position: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left';
  welcomeMessage: string;
}

export interface WidgetConfigResponse {
  success: boolean;
  client_name?: string;
  widget_config?: WidgetConfig;
  error?: string;
}

// ✅ UPDATED: Constructor now takes apiKey string instead of config object
export interface GreetoChatWidget {
  init(): Promise<void>;
  destroy(): void;
  open(): void;
  close(): void;
}

export interface GreetoChatWidgetConstructor {
  new (apiKey: string): GreetoChatWidget; // ✅ Changed from config object to apiKey string
}

// Extend Window interface
declare global {
  interface Window {
    GreetoChatWidget: GreetoChatWidgetConstructor;
    greetoChat?: GreetoChatWidget;
  }
}

// For module augmentation
export {};
