// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/config/api.ts

import axios from 'axios';

// ✅ Get from environment variables
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';
const DEFAULT_API_KEY = import.meta.env.VITE_DEV_API_KEY || 'kula-key-test-123';

// ✅ In-memory API key (no localStorage needed)
let currentApiKey = DEFAULT_API_KEY;

// Create axios instance with base config
const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
    'x-api-key': currentApiKey,
  },
  timeout: 30000, // 30 seconds
});

// Request interceptor - dynamically inject current API key
apiClient.interceptors.request.use(
  (config) => {
    // ✅ Always use latest API key (in case it changed)
    config.headers['x-api-key'] = currentApiKey;
    console.log(`[Greeto Widget] API Request: ${config.method?.toUpperCase()} ${config.url}`);
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor for error handling
apiClient.interceptors.response.use(
  (response) => {
    console.log(`[Greeto Widget] API Response: ${response.status}`);
    return response;
  },
  (error) => {
    console.error('[Greeto Widget] API Error:', error.response?.data || error.message);
    
    // ✅ Add user-friendly error messages
    if (error.response) {
      const status = error.response.status;
      if (status === 401) {
        error.userMessage = 'Authentication failed. Please check your API key.';
      } else if (status === 429) {
        error.userMessage = 'Too many requests. Please wait a moment.';
      } else if (status >= 500) {
        error.userMessage = 'Server error. Please try again later.';
      } else {
        error.userMessage = error.response.data?.error || 'Something went wrong.';
      }
    } else if (error.request) {
      error.userMessage = 'Cannot reach server. Please check your connection.';
    } else {
      error.userMessage = 'An unexpected error occurred.';
    }
    
    return Promise.reject(error);
  }
);

/**
 * ✅ Update API key dynamically (called by embed.ts in production mode)
 * @param newApiKey - API key from script tag data-api-key attribute
 */
export const setApiKey = (newApiKey: string) => {
  currentApiKey = newApiKey;
  apiClient.defaults.headers['x-api-key'] = newApiKey;
  console.log('[Greeto Widget] API key updated:', newApiKey.substring(0, 15) + '...');
};

/**
 * ✅ Update base URL (useful for switching environments)
 * @param newBaseUrl - New API base URL
 */
export const setBaseUrl = (newBaseUrl: string) => {
  apiClient.defaults.baseURL = newBaseUrl;
  console.log('[Greeto Widget] Base URL updated to:', newBaseUrl);
};

/**
 * ✅ Get current API key (for debugging)
 */
export const getCurrentApiKey = () => currentApiKey;

/**
 * ✅ Submit lead form data
 * @param leadData - Lead form data with visitorId, name, email, phone, company, conversationId (required)
 * @returns Promise with lead submission response
 */
export const submitLead = async (leadData: {
  visitorId: string;
  name: string;
  email: string;
  phone?: string;
  company?: string;
  conversationId: number;
}) => {
  try {
    console.log('[Greeto Widget] Submitting lead:', leadData);
    const { data } = await apiClient.post('/leads', leadData);
    console.log('[Greeto Widget] Lead submitted successfully, raw response:', data);
    
    // Ensure response has success field
    const response = {
      success: data?.success !== false,
      ...data,
    };
    
    console.log('[Greeto Widget] Lead response with success flag:', response);
    return response;
  } catch (error) {
    console.error('[Greeto Widget] Lead submission failed:', error);
    throw error;
  }
};

/**
 * ✅ Update lead details
 * @param visitorId - Visitor ID
 * @param updateData - Partial lead update (name, email, phone, company)
 * @returns Promise with updated lead response
 */
export const updateLead = async (visitorId: string, updateData: {
  name?: string;
  email?: string;
  phone?: string;
  company?: string;
}) => {
  try {
    console.log('[Greeto Widget] Updating lead:', visitorId, updateData);
    const { data } = await apiClient.put(`/leads/${visitorId}`, updateData);
    console.log('[Greeto Widget] Lead updated successfully:', data);
    return data;
  } catch (error) {
    console.error('[Greeto Widget] Lead update failed:', error);
    throw error;
  }
};

/**
 * ✅ Get lead details for current visitor
 * @param visitorId - Visitor ID
 * @returns Promise with lead data if exists, or null if not found
 */
/**
 * ✅ Fetch widget configuration including starter_suggestions
 * @returns Promise with widget config data
 */
export const getWidgetConfig = async () => {
  try {
    console.log('[Greeto Widget] Fetching widget config');
    const { data } = await apiClient.get('/widget/config');
    console.log('[Greeto Widget] Widget config fetched:', data);
    
    // ✅ Store client_name in sessionStorage immediately for getVisitorId() to access
    if (data?.client_name) {
      sessionStorage.setItem('greeto_client_name', data.client_name);
      console.log('[Greeto Chat] Client name cached in sessionStorage (from api.ts):', data.client_name);
    }
    
    return data;
  } catch (error) {
    console.error('[Greeto Widget] Failed to fetch widget config:', error);
    return null;
  }
};

export const getLead = async (visitorId: string) => {
  try {
    console.log('[Greeto Widget] Fetching lead for visitor:', visitorId);
    const { data } = await apiClient.get(`/leads/${visitorId}`);
    console.log('[Greeto Widget] Lead fetched successfully:', data);
    return data.lead || null;
  } catch (error: any) {
    // 404 means lead doesn't exist yet, which is not an error
    if (error.response?.status === 404) {
      console.log('[Greeto Widget] No existing lead found for visitor');
      return null;
    }
    console.error('[Greeto Widget] Failed to fetch lead:', error);
    throw error;
  }
};

/**
 * ✅ Retrieve client + subscription status using admin endpoints.
 * The backend should restrict results to the client tied to the API key.
 * Returns both statuses if available.
 */
export const fetchClientAndSubscriptionStatus = async (): Promise<{
  clientStatus?: string;
  subscriptionStatus?: string;
}> => {
  try {
    console.log('[Greeto Widget] Fetching client/subscription status via /chat/client-status');

    const { data } = await apiClient.get('/chat/client-status');
    console.log('[Greeto Widget] /chat/client-status response:', data);

    // Defensive parsing: different backends may return different shapes
    // Try common field names first
    let clientStatus = data?.client_status || data?.client?.status || data?.status || data?.clientStatus;
    let subscriptionStatus = data?.subscription_status || data?.subscription?.status || data?.subscriptionStatus;

    // Fallback: if response contains a clients array, pick the first
    if ((!clientStatus || !subscriptionStatus) && Array.isArray(data?.clients) && data.clients.length > 0) {
      const c = data.clients[0];
      clientStatus = clientStatus || c.status;
      subscriptionStatus = subscriptionStatus || c.subscription?.status;
    }

    console.log('[Greeto Widget] Parsed statuses -> client:', clientStatus, 'subscription:', subscriptionStatus);
    return { clientStatus, subscriptionStatus };
  } catch (error) {
    console.error('[Greeto Widget] Error fetching client/subscription status:', error);
    return {};
  }
};

export default apiClient;
