// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/config/api.ts

import axios from 'axios';

// ✅ Get from environment variables
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';
const DEFAULT_API_KEY = import.meta.env.VITE_DEV_API_KEY || 'kula-key-test-123';

// ✅ In-memory API key (no localStorage needed)
let currentApiKey = DEFAULT_API_KEY;

// Create axios instance with base config
const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
    'x-api-key': currentApiKey,
  },
  timeout: 30000, // 30 seconds
});

// Request interceptor - dynamically inject current API key
apiClient.interceptors.request.use(
  (config) => {
    // ✅ Always use latest API key (in case it changed)
    config.headers['x-api-key'] = currentApiKey;
    console.log(`[Greeto Widget] API Request: ${config.method?.toUpperCase()} ${config.url}`);
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response interceptor for error handling
apiClient.interceptors.response.use(
  (response) => {
    console.log(`[Greeto Widget] API Response: ${response.status}`);
    return response;
  },
  (error) => {
    console.error('[Greeto Widget] API Error:', error.response?.data || error.message);
    
    // ✅ Add user-friendly error messages
    if (error.response) {
      const status = error.response.status;
      if (status === 401) {
        error.userMessage = 'Authentication failed. Please check your API key.';
      } else if (status === 429) {
        error.userMessage = 'Too many requests. Please wait a moment.';
      } else if (status >= 500) {
        error.userMessage = 'Server error. Please try again later.';
      } else {
        error.userMessage = error.response.data?.error || 'Something went wrong.';
      }
    } else if (error.request) {
      error.userMessage = 'Cannot reach server. Please check your connection.';
    } else {
      error.userMessage = 'An unexpected error occurred.';
    }
    
    return Promise.reject(error);
  }
);

/**
 * ✅ Update API key dynamically (called by embed.ts in production mode)
 * @param newApiKey - API key from script tag data-api-key attribute
 */
export const setApiKey = (newApiKey: string) => {
  currentApiKey = newApiKey;
  apiClient.defaults.headers['x-api-key'] = newApiKey;
  console.log('[Greeto Widget] API key updated:', newApiKey.substring(0, 15) + '...');
};

/**
 * ✅ Update base URL (useful for switching environments)
 * @param newBaseUrl - New API base URL
 */
export const setBaseUrl = (newBaseUrl: string) => {
  apiClient.defaults.baseURL = newBaseUrl;
  console.log('[Greeto Widget] Base URL updated to:', newBaseUrl);
};

/**
 * ✅ Get current API key (for debugging)
 */
export const getCurrentApiKey = () => currentApiKey;

/**
 * ✅ Submit lead form data
 * @param leadData - Lead form data with visitorId, name, email, phone, company
 * @returns Promise with lead submission response
 */
export const submitLead = async (leadData: {
  visitorId: string;
  name: string;
  email: string;
  phone?: string;
  company?: string;
  conversationId?: number;
}) => {
  try {
    console.log('[Greeto Widget] Submitting lead:', leadData);
    const { data } = await apiClient.post('/leads', leadData);
    console.log('[Greeto Widget] Lead submitted successfully:', data);
    return data;
  } catch (error) {
    console.error('[Greeto Widget] Lead submission failed:', error);
    throw error;
  }
};

/**
 * ✅ Update lead details
 * @param visitorId - Visitor ID
 * @param updateData - Partial lead update (name, email, phone, company)
 * @returns Promise with updated lead response
 */
export const updateLead = async (visitorId: string, updateData: {
  name?: string;
  email?: string;
  phone?: string;
  company?: string;
}) => {
  try {
    console.log('[Greeto Widget] Updating lead:', visitorId, updateData);
    const { data } = await apiClient.put(`/leads/${visitorId}`, updateData);
    console.log('[Greeto Widget] Lead updated successfully:', data);
    return data;
  } catch (error) {
    console.error('[Greeto Widget] Lead update failed:', error);
    throw error;
  }
};

/**
 * ✅ Get lead details for current visitor
 * @param visitorId - Visitor ID
 * @returns Promise with lead data if exists, or null if not found
 */
export const getLead = async (visitorId: string) => {
  try {
    console.log('[Greeto Widget] Fetching lead for visitor:', visitorId);
    const { data } = await apiClient.get(`/leads/${visitorId}`);
    console.log('[Greeto Widget] Lead fetched successfully:', data);
    return data.lead || null;
  } catch (error: any) {
    // 404 means lead doesn't exist yet, which is not an error
    if (error.response?.status === 404) {
      console.log('[Greeto Widget] No existing lead found for visitor');
      return null;
    }
    console.error('[Greeto Widget] Failed to fetch lead:', error);
    throw error;
  }
};

export default apiClient;
