// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/components/ChatWidget.tsx

import { useState, useEffect } from 'react';
import ChatWindow from './ChatWindow';
import chatIcon from '../assets/chat-icon.svg';
import closeIcon from '../assets/close-icon.svg';
import minimizeIcon from '../assets/minimize-icon.svg';

const ChatWidget = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [position, setPosition] = useState('bottom-right');

  // Get position from container data attribute
  useEffect(() => {
    const container = document.getElementById('greeto-chat-widget-container');
    const configPosition = container?.getAttribute('data-position') || 'bottom-right';
    setPosition(configPosition);
  }, []);

  // Listen for global events
  useEffect(() => {
    const handleOpen = () => setIsOpen(true);
    const handleClose = () => setIsOpen(false);

    window.addEventListener('greeto-chat-open', handleOpen);
    window.addEventListener('greeto-chat-close', handleClose);

    return () => {
      window.removeEventListener('greeto-chat-open', handleOpen);
      window.removeEventListener('greeto-chat-close', handleClose);
    };
  }, []);

  // Calculate position classes based on config
  const getPositionClasses = (isWindow: boolean = false) => {
    switch (position) {
      case 'bottom-left':
        return isWindow 
          ? `bottom-20 left-4`
          : `bottom-4 left-4`;
      case 'top-right':
        return isWindow 
          ? `top-20 right-4`
          : `top-4 right-4`;
      case 'top-left':
        return isWindow 
          ? `top-20 left-4`
          : `top-4 left-4`;
      case 'bottom-right':
      default:
        return isWindow 
          ? `bottom-20 right-4`
          : `bottom-4 right-4`;
    }
  };


  return (
    <>
      {/* Chat Window - 70% of screen height with spacing from icon */}
      {isOpen && (
        <div 
          className={`
            fixed ${getPositionClasses(true)} 
            w-full max-w-[400px] sm:w-[400px]
            h-[70vh]
            max-h-[700px]
            min-h-[400px]
            z-[999998] 
            animate-slide-up
          `}
        >
          <ChatWindow onClose={() => setIsOpen(false)} minimizeIcon={minimizeIcon} />
        </div>
      )}

      {/* Chat Button - Clean, no backgrounds */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`
          icon-button
          fixed ${getPositionClasses(false)} 
          w-14 h-14 
          bg-transparent
          border-0
          p-0
          flex items-center justify-center 
          transition-all duration-300 hover:scale-110 
          z-[999999] 
          focus:outline-none 
          cursor-pointer 
          group
        `}
        aria-label={isOpen ? 'Close chat' : 'Open chat'}
      >
        {isOpen ? (
          // Close icon - same style as chat icon
          <img 
            src={closeIcon} 
            alt="Close" 
            className="w-14 h-14 drop-shadow-2xl transition-transform duration-300 group-hover:rotate-90"
          />
        ) : (
          // Chat icon
          <img 
            src={chatIcon} 
            alt="Chat" 
            className="w-14 h-14 drop-shadow-2xl"
          />
        )}
      </button>
    </>
  );
};

export default ChatWidget;
