// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/components/ChatInput.tsx

import React from 'react';

interface ChatInputProps {
  value: string;
  onChange: (value: string) => void;
  onSend: (e: React.FormEvent) => void;
  disabled?: boolean;
}

const ChatInput: React.FC<ChatInputProps> = ({ value, onChange, onSend, disabled }) => (
  <form onSubmit={onSend} className="flex gap-2">
    <input
      type="text"
      className="flex-1 border border-gray-300 rounded-full px-5 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-theme-primary-light focus:border-theme-primary transition-all placeholder:text-gray-400"
      placeholder="Type your message..."
      value={value}
      onChange={e => onChange(e.target.value)}
      disabled={disabled}
      autoComplete="off"
    />
    <button 
      type="submit"
      className="bg-theme-primary text-white px-6 py-3 rounded-full font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-theme-primary-hover transition-all shadow-md hover:shadow-lg active:scale-95 flex items-center justify-center"
      disabled={disabled || !value.trim()}
    >
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
      </svg>
    </button>
  </form>
);

export default ChatInput;
