// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/components/ChatWindow.tsx

import { useState, useEffect, useRef } from 'react';
import MessageBubble from './MessageBubble';
import ChatInput from './ChatInput';
import type { Message, ChatResponse } from '../types/chat';
import apiClient from '../config/api';

interface ChatWindowProps {
  onClose?: () => void;
  minimizeIcon: string;
}

const getVisitorId = (): string => {
  let visitorId = sessionStorage.getItem('greeto_visitor_id');
  if (!visitorId) {
    visitorId = `visitor_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    sessionStorage.setItem('greeto_visitor_id', visitorId);
  }
  return visitorId;
};

function ChatWindow({ onClose, minimizeIcon }: ChatWindowProps) {
  const welcomeMessage =
    document.getElementById('greeto-chat-widget-container')?.getAttribute('data-welcome-message')
    || 'Hi! How can I help you today?';

  const [messages, setMessages] = useState<Message[]>([
    { role: 'assistant', content: welcomeMessage }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [conversationId, setConversationId] = useState<number | null>(null);
  const [visitorId] = useState<string>(getVisitorId());
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(() => {
    const loadConversationHistory = async () => {
      const savedConversationId = sessionStorage.getItem('greeto_conversation_id');
      if (!savedConversationId) return;

      try {
        const { data } = await apiClient.get(`/chat/history/${savedConversationId}`);

        if (data.messages && data.messages.length > 0) {
          setConversationId(Number(savedConversationId));
          const loadedMessages: Message[] = data.messages.map((msg: any) => ({
            role: msg.role as 'user' | 'assistant',
            content: msg.content
          }));
          setMessages([
            { role: 'assistant', content: welcomeMessage },
            ...loadedMessages
          ]);
        }
      } catch (error) {
        console.error('Failed to load conversation history:', error);
        sessionStorage.removeItem('greeto_conversation_id');
      }
    };

    loadConversationHistory();
  }, [welcomeMessage]);

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMessage = input.trim();
    setMessages(prevMessages => [...prevMessages, { role: 'user', content: userMessage }]);
    setLoading(true);
    setInput('');

    try {
      const requestBody: any = {
        message: userMessage,
        visitorId: visitorId
      };

      if (conversationId) {
        requestBody.conversationId = conversationId;
      }

      const { data } = await apiClient.post<ChatResponse>('/chat', requestBody);

      if (!conversationId && data.conversationId) {
        setConversationId(data.conversationId);
        sessionStorage.setItem('greeto_conversation_id', data.conversationId.toString());
      }

      setMessages(prevMessages => [
        ...prevMessages,
        { role: 'assistant', content: data.response }
      ]);
    } catch (error: any) {
      console.error('Error sending message:', error);
      const errorMessage = error.userMessage || 'Sorry, I encountered an error. Please try again.';
      setMessages(prevMessages => [
        ...prevMessages,
        { role: 'assistant', content: errorMessage }
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-full w-full max-w-[400px] bg-white rounded-2xl shadow-widget-lg flex flex-col overflow-hidden">
      {/* Header - Fixed at top with minimize icon */}
      <div className="bg-gradient-to-r from-theme-primary to-theme-secondary text-white px-4 py-3 flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-3">
          {/* Avatar */}
          <div className="w-10 h-10 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-sm flex-shrink-0">
            <svg className="w-6 h-6 text-white" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clipRule="evenodd" />
            </svg>
          </div>

          <div className="min-w-0">
            <h3 className="font-semibold text-sm">Chat Support</h3>
            <div className="flex items-center gap-1.5 text-xs text-white/80">
              <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse flex-shrink-0"></div>
              <span>Online</span>
            </div>
          </div>
        </div>

        {/* Minimize button - Pure Tailwind CSS */}
        {onClose && (
          <button
            onClick={onClose}
            className="bg-transparent hover:bg-white/10 active:bg-white/20 rounded-lg p-2 transition-all duration-200 flex-shrink-0 group"
            aria-label="Minimize chat"
          >
            <img
              src={minimizeIcon}
              alt="Minimize"
              className="w-5 h-5 block transition-transform duration-200 group-hover:scale-110"
            />
          </button>
        )}
      </div>

      {/* Messages - Flexible scrollable area (takes remaining space) */}
      <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3 bg-gradient-to-b from-gray-50 to-white min-h-0">
        {messages.map((msg, idx) => (
          <MessageBubble key={idx} role={msg.role} content={msg.content} />
        ))}

        {/* Typing indicator */}
        {loading && (
          <div className="flex justify-start animate-slide-in">
            <div className="bg-gray-200 rounded-2xl px-4 py-3 flex items-center gap-2">
              <div className="flex gap-1">
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
              </div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input - Fixed at bottom */}
      <div className="p-4 bg-white border-t border-gray-100 flex-shrink-0">
        <ChatInput
          value={input}
          onChange={setInput}
          onSend={sendMessage}
          disabled={loading}
        />
      </div>

      {/* Powered by Greeto - branding*/}
      <div className="px-4 py-3 text-center border-t border-gray-200 bg-gradient-to-b from-white to-gray-50">
        <a
          href="https://greeto.ai"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 transition-all duration-200 hover:-translate-y-0.5"
        >
          <span>Powered by</span>
          <span className="font-semibold text-blue-600 hover:text-blue-700">
            Greeto
          </span>
        </a>
      </div>
    </div>
  );
}

export default ChatWindow;
