// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/components/LeadForm.tsx - Lead capture form component

import React, { useState, useEffect } from 'react';
import { submitLead, updateLead } from '../config/api';
import type { LeadFormData, LeadFormErrors, LeadSubmitResponse } from '../types/lead';

interface LeadFormProps {
  visitorId: string;
  conversationId?: number | null;
  initialData?: LeadFormData;
  isEditMode?: boolean;
  onSuccess: (response: LeadSubmitResponse) => void;
  onCancel: () => void;
}

const LeadForm: React.FC<LeadFormProps> = ({ 
  visitorId, 
  conversationId, 
  initialData,
  isEditMode = false,
  onSuccess, 
  onCancel 
}) => {
  const [formData, setFormData] = useState<LeadFormData>(
    initialData || {
      name: '',
      email: '',
      phone: '',
      company: '',
    }
  );

  const [errors, setErrors] = useState<LeadFormErrors>({});
  const [loading, setLoading] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);

  // ✅ Email validation regex (basic format check)
  const isValidEmail = (email: string): boolean => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  };

  // ✅ Validate form data
  const validateForm = (): boolean => {
    const newErrors: LeadFormErrors = {};

    // Name validation
    const trimmedName = formData.name.trim();
    if (!trimmedName) {
      newErrors.name = 'Name is required';
    }

    // Email validation
    const trimmedEmail = formData.email.trim();
    if (!trimmedEmail) {
      newErrors.email = 'Email is required';
    } else if (!isValidEmail(trimmedEmail)) {
      newErrors.email = 'Please enter a valid email address';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // ✅ Handle input changes
  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    // Clear error for this field when user starts typing
    if (errors[name as keyof LeadFormErrors]) {
      setErrors((prev) => ({
        ...prev,
        [name]: undefined,
      }));
    }
  };

  // ✅ Handle form submission (create or update)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setApiError(null);

    if (!validateForm()) {
      return;
    }

    setLoading(true);

    try {
      let response;

      if (isEditMode) {
        // Update mode: send all fields (including empty ones to allow clearing)
        const updateData: any = {
          name: formData.name.trim(),
          email: formData.email.trim(),
          phone: formData.phone.trim() || null,
          company: formData.company.trim() || null,
        };

        const result = await updateLead(visitorId, updateData);
        response = {
          success: result.success,
          leadId: result.lead?.id,
          isNew: false,
          lead: result.lead,
        };
      } else {
        // Create mode: full submission
        const submitData = {
          visitorId,
          name: formData.name.trim(),
          email: formData.email.trim(),
          ...(formData.phone.trim() && { phone: formData.phone.trim() }),
          ...(formData.company.trim() && { company: formData.company.trim() }),
          ...(conversationId && { conversationId }),
        };

        response = await submitLead(submitData);
      }

      if (response.success) {
        console.log('[Greeto Widget] Lead submission successful');
        onSuccess(response);
        onCancel();
      } else {
        setApiError(response.error || 'Failed to submit lead. Please try again.');
      }
    } catch (error: any) {
      const errorMessage =
        error.userMessage || error.response?.data?.error || 'Failed to submit lead. Please try again.';
      setApiError(errorMessage);
      console.error('[Greeto Widget] Lead submission error:', error);
    } finally {
      setLoading(false);
    }
  };

  // ✅ Check if form is valid (for submit button disabled state)
  const isFormValid =
    formData.name.trim().length > 0 &&
    formData.email.trim().length > 0 &&
    isValidEmail(formData.email.trim()) &&
    Object.keys(errors).length === 0;

  return (
    <div className="flex flex-col h-full bg-gray-50 rounded-lg">
      {/* Header */}
      <div className="flex items-center justify-between mb-2 px-4 pt-4 flex-shrink-0">
        <h3 className="font-semibold text-gray-900">
          {isEditMode ? 'Edit your details' : 'Leave your details'}
        </h3>
        <button
          onClick={onCancel}
          className="text-gray-400 hover:text-gray-600 transition-colors"
          aria-label="Close lead form"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Scrollable content area */}
      <div className="flex-1 overflow-y-auto px-4 pb-4">
        {/* Error message */}
        {apiError && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-md mb-3">
            <p className="text-sm text-red-700">{apiError}</p>
          </div>
        )}

        {/* Form */}
        <form id="lead-form" onSubmit={handleSubmit} className="flex flex-col gap-3">
        {/* Name field */}
        <div className="flex flex-col gap-1">
          <label htmlFor="lead-name" className="text-sm font-medium text-gray-700">
            Name *
          </label>
          <input
            id="lead-name"
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            placeholder="Your full name"
            disabled={loading}
            className={`px-3 py-2 border rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-theme-primary transition-colors ${
              errors.name
                ? 'border-red-300 focus:ring-red-200'
                : 'border-gray-300 focus:border-theme-primary'
            } disabled:bg-gray-100 disabled:cursor-not-allowed`}
          />
          {errors.name && <span className="text-xs text-red-600">{errors.name}</span>}
        </div>

        {/* Email field */}
        <div className="flex flex-col gap-1">
          <label htmlFor="lead-email" className="text-sm font-medium text-gray-700">
            Email *
          </label>
          <input
            id="lead-email"
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            placeholder="your@email.com"
            disabled={loading}
            className={`px-3 py-2 border rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-theme-primary transition-colors ${
              errors.email
                ? 'border-red-300 focus:ring-red-200'
                : 'border-gray-300 focus:border-theme-primary'
            } disabled:bg-gray-100 disabled:cursor-not-allowed`}
          />
          {errors.email && <span className="text-xs text-red-600">{errors.email}</span>}
        </div>

        {/* Phone field (optional) */}
        <div className="flex flex-col gap-1">
          <label htmlFor="lead-phone" className="text-sm font-medium text-gray-700">
            Phone
          </label>
          <input
            id="lead-phone"
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            placeholder="+1234567890 (optional)"
            disabled={loading}
            className="px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-theme-primary focus:border-theme-primary transition-colors disabled:bg-gray-100 disabled:cursor-not-allowed"
          />
        </div>

        {/* Company field (optional) */}
        <div className="flex flex-col gap-1">
          <label htmlFor="lead-company" className="text-sm font-medium text-gray-700">
            Company
          </label>
          <input
            id="lead-company"
            type="text"
            name="company"
            value={formData.company}
            onChange={handleChange}
            placeholder="Your company (optional)"
            disabled={loading}
            className="px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-theme-primary focus:border-theme-primary transition-colors disabled:bg-gray-100 disabled:cursor-not-allowed"
          />
        </div>
        </form>
      </div>

      {/* Action buttons - Fixed at bottom */}
      <div className="flex gap-2 px-4 pb-4 flex-shrink-0 border-t border-gray-200 pt-3">
        <button
          type="submit"
          form="lead-form"
          disabled={!isFormValid || loading}
          className="flex-1 bg-theme-primary text-text-on-primary px-4 py-2 rounded-md font-semibold text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-theme-primary-hover transition-colors active:scale-95"
        >
          {loading ? 'Updating...' : isEditMode ? 'Update' : 'Submit'}
        </button>
        <button
          type="button"
          onClick={onCancel}
          disabled={loading}
          className="flex-1 bg-gray-200 text-gray-700 px-4 py-2 rounded-md font-semibold text-sm disabled:opacity-50 disabled:cursor-not-allowed hover:bg-gray-300 transition-colors active:scale-95"
        >
          Cancel
        </button>
      </div>
    </div>
  );
};

export default LeadForm;
