// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/utils/uuid.ts
// UUID v4 generation utility for unique visitor identification

/**
 * Generate a UUID v4 identifier
 * Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 * Used for unique visitor tracking across browser sessions
 * 
 * @returns {string} UUID v4 format string
 */
export const generateUUID = (): string => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

/**
 * Get or create a persistent visitor ID using localStorage
 * Visitor ID persists across browser sessions
 * 
 * @returns {string} UUID v4 format visitor ID
 */
export const getVisitorId = (): string => {
  const STORAGE_KEY = 'greeto_visitor_id';
  
  // Try to retrieve existing visitor ID from localStorage
  let visitorId = localStorage.getItem(STORAGE_KEY);
  
  // If not found, generate a new UUID and store it
  if (!visitorId) {
    visitorId = generateUUID();
    try {
      localStorage.setItem(STORAGE_KEY, visitorId);
      console.log('[Greeto Chat] New visitor ID created:', visitorId);
    } catch (error) {
      // Fallback if localStorage is not available (private browsing, etc.)
      console.warn('[Greeto Chat] localStorage not available, using session-only ID:', visitorId);
    }
  } else {
    console.log('[Greeto Chat] Existing visitor ID loaded:', visitorId);
  }
  
  return visitorId;
};

/**
 * Clear the stored visitor ID (useful for logout/reset scenarios)
 */
export const clearVisitorId = (): void => {
  try {
    localStorage.removeItem('greeto_visitor_id');
    console.log('[Greeto Chat] Visitor ID cleared');
  } catch (error) {
    console.warn('[Greeto Chat] Failed to clear visitor ID:', error);
  }
};
