// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/embed.ts - Production widget loader

import './index.css';
import { createRoot } from 'react-dom/client';
import React from 'react';
import Widget from './widget';
import { setApiKey, fetchClientAndSubscriptionStatus } from './config/api';

interface WidgetConfig {
  primaryColor: string;
  secondaryColor: string;
  position: string;
  welcomeMessage: string;
}

interface WidgetConfigResponse {
  success: boolean;
  client_name?: string;
  widget_config?: WidgetConfig;
  error?: string;
}

class GreetoChatWidget {
  private container: HTMLDivElement | null = null;
  private root: any = null;
  private apiKey: string = '';
  private isInitialized: boolean = false;
  private cssLoaded: boolean = false;

  constructor(apiKey: string) {
    this.apiKey = apiKey;
    setApiKey(apiKey);
  }

  async init(): Promise<void> {
    if (this.isInitialized) {
      console.warn('[Greeto Chat] Widget already initialized');
      return;
    }

    try {
      console.log('[Greeto Chat] Initializing widget...');

      // ✅ Check client/subscription status FIRST (before any other calls)
      const { clientStatus, subscriptionStatus } = await fetchClientAndSubscriptionStatus();
      console.log('[Greeto Chat] Status check result:', { clientStatus, subscriptionStatus });

      // Hide widget if client is inactive AND subscription is expired or inactive
      const shouldHide = clientStatus === 'inactive' && (subscriptionStatus === 'expired' || subscriptionStatus === 'inactive');
      if (shouldHide) {
        console.warn('[Greeto Chat] Hiding widget: client inactive and subscription', subscriptionStatus);
        this.isInitialized = true;
        return;
      }

      // ✅ Auto-load CSS
      await this.loadStylesheet();

      // ✅ Fetch config from backend (only if statuses allow)
      let config: WidgetConfigResponse | null = null;
      try {
        config = await this.fetchWidgetConfig();
      } catch (cfgError: any) {
        console.warn('[Greeto Chat] Widget config fetch error:', cfgError?.message || cfgError);
        // Fallback to default config
        this.createContainer();
        this.applyDefaultConfig();
        this.renderWidget();
        this.isInitialized = true;
        return;
      }

      // Render with fetched config
      if (config && config.success) {
        this.createContainer();
        this.applyConfig(config);
        this.renderWidget();
        this.isInitialized = true;
        console.log('[Greeto Chat] Widget initialized successfully');
      } else {
        console.warn('[Greeto Chat] Config returned unsuccessful, using defaults');
        this.createContainer();
        this.applyDefaultConfig();
        this.renderWidget();
        this.isInitialized = true;
      }
    } catch (error) {
      console.error('[Greeto Chat] Initialization failed:', error);
      // Fallback: load CSS, create container, apply defaults, render
      await this.loadStylesheet();
      this.createContainer();
      this.applyDefaultConfig();
      this.renderWidget();
      this.isInitialized = true;
    }
  }

  // ✅ NEW: Auto-load CSS method
  private async loadStylesheet(): Promise<void> {
    if (this.cssLoaded) {
      return;
    }

    // Check if CSS already loaded by user
    if (document.querySelector('link[href*="widget.css"]')) {
      console.log('[Greeto Chat] CSS already loaded');
      this.cssLoaded = true;
      return;
    }

    // Get script source to determine CSS location
    const scriptTag = document.currentScript as HTMLScriptElement || 
                      document.querySelector('script[src*="widget.js"]') as HTMLScriptElement;
    
    if (!scriptTag?.src) {
      console.warn('[Greeto Chat] Could not determine CSS URL, styles may not load');
      return;
    }

    const cssUrl = scriptTag.src.replace('widget.js', 'widget.css');
    
    return new Promise((resolve) => {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = cssUrl;
      
      link.onload = () => {
        console.log('[Greeto Chat] CSS loaded successfully');
        this.cssLoaded = true;
        resolve();
      };
      
      link.onerror = () => {
        console.warn('[Greeto Chat] CSS failed to load, using inline styles');
        this.cssLoaded = true;
        resolve(); // Don't reject, continue with inline styles
      };
      
      document.head.appendChild(link);
      
      // Timeout fallback (CSS should load quickly)
      setTimeout(() => {
        if (!this.cssLoaded) {
          console.log('[Greeto Chat] CSS load timeout, continuing...');
          this.cssLoaded = true;
          resolve();
        }
      }, 3000);
    });
  }


  private async fetchWidgetConfig(): Promise<WidgetConfigResponse> {
    const API_BASE_URL = (window as any).__KULA_CHAT_API_URL__ || 'http://localhost:5001/api';
    
    const response = await fetch(`${API_BASE_URL}/widget/config`, {
      headers: {
        'X-API-Key': this.apiKey,
        'Content-Type': 'application/json'
      }
    });

    // Try to parse JSON body for useful backend error messages
    let body: any = null;
    try {
      body = await response.json();
    } catch (err) {
      // ignore JSON parse errors
    }

    if (!response.ok) {
      const errMsg = body?.error || `Config fetch failed: ${response.status}`;
      throw new Error(errMsg);
    }

    return body as WidgetConfigResponse;
  }

  private createContainer(): void {
    // ✅ IMPROVED: Check if container already exists (manually added by user)
    this.container = document.getElementById('greeto-chat-widget-container') as HTMLDivElement;
    
    if (!this.container) {
      this.container = document.createElement('div');
      this.container.id = 'greeto-chat-widget-container';
      document.body.appendChild(this.container);
      console.log('[Greeto Chat] Container auto-created');
    } else {
      console.log('[Greeto Chat] Using existing container');
    }
  }

  private applyConfig(config: WidgetConfigResponse): void {
    if (!this.container) return;

    const widgetConfig = config.widget_config;
    if (!widgetConfig) {
      console.warn('[Greeto Chat] No widget_config provided, falling back to defaults');
      this.applyDefaultConfig();
      return;
    }
    
    // Set CSS variables
    this.container.style.setProperty('--color-theme-primary', widgetConfig.primaryColor);
    this.container.style.setProperty('--color-theme-secondary', widgetConfig.secondaryColor);
    this.container.style.setProperty('--color-theme-primary-hover', widgetConfig.secondaryColor);
    
    // Calculate light color
    const primaryRgb = this.hexToRgb(widgetConfig.primaryColor);
    const lightColor = primaryRgb 
      ? `rgba(${primaryRgb.r}, ${primaryRgb.g}, ${primaryRgb.b}, 0.2)` 
      : '#dbeafe';
    this.container.style.setProperty('--color-theme-primary-light', lightColor);
    
    // Calculate contrast text colors based on background luminance
    const primaryTextColor = this.getContrastTextColor(widgetConfig.primaryColor);
    const secondaryTextColor = this.getContrastTextColor(widgetConfig.secondaryColor);
    this.container.style.setProperty('--color-text-on-primary', primaryTextColor);
    this.container.style.setProperty('--color-text-on-secondary', secondaryTextColor);
    
    // Store config as data attributes
    this.container.setAttribute('data-position', widgetConfig.position);
    this.container.setAttribute('data-welcome-message', widgetConfig.welcomeMessage);
    
    console.log('[Greeto Chat] Config applied:', widgetConfig);
  }

  private applyDefaultConfig(): void {
    if (!this.container) return;

    this.container.style.setProperty('--color-theme-primary', '#2563EB');
    this.container.style.setProperty('--color-theme-secondary', '#1d4ed8');
    this.container.style.setProperty('--color-theme-primary-hover', '#1d4ed8');
    this.container.style.setProperty('--color-theme-primary-light', '#dbeafe');
    
    // Calculate contrast text colors for default theme
    const primaryTextColor = this.getContrastTextColor('#2563EB');
    const secondaryTextColor = this.getContrastTextColor('#1d4ed8');
    this.container.style.setProperty('--color-text-on-primary', primaryTextColor);
    this.container.style.setProperty('--color-text-on-secondary', secondaryTextColor);
    
    this.container.setAttribute('data-position', 'bottom-right');
    this.container.setAttribute('data-welcome-message', 'Hi! How can I help you today?');
    
    console.log('[Greeto Chat] Using default config');
  }

  private hexToRgb(hex: string): { r: number; g: number; b: number } | null {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : null;
  }

  private getLuminance(hex: string): number {
    const rgb = this.hexToRgb(hex);
    if (!rgb) return 0.5; // Default to mid-range
    
    // Calculate relative luminance using WCAG formula
    const luminance = (0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b) / 255;
    return luminance;
  }

  private getContrastTextColor(hex: string): string {
    const luminance = this.getLuminance(hex);
    // If luminance > 0.5, use dark text; otherwise use white text
    return luminance > 0.5 ? '#1f2937' : '#ffffff';
  }

  private renderWidget(): void {
    if (!this.container) return;

    this.root = createRoot(this.container);
    this.root.render(React.createElement(Widget));
  }

  destroy(): void {
    if (this.root) {
      this.root.unmount();
      this.root = null;
    }
    if (this.container) {
      this.container.remove();
      this.container = null;
    }
    this.isInitialized = false;
    this.cssLoaded = false;
    console.log('[Greeto Chat] Widget destroyed');
  }

  open(): void {
    window.dispatchEvent(new Event('greeto-chat-open'));
  }

  close(): void {
    window.dispatchEvent(new Event('greeto-chat-close'));
  }
}

// Auto-initialize from script tag
if (typeof window !== 'undefined') {
  (window as any).GreetoChatWidget = GreetoChatWidget;

  const scriptTag = document.currentScript as HTMLScriptElement;
  if (scriptTag) {
    const apiKey = scriptTag.getAttribute('data-api-key');

    if (apiKey) {
      console.log('[Greeto Chat] Found API key in script tag');
      
      (window as any).greetoChat = new GreetoChatWidget(apiKey);

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', () => {
          (window as any).greetoChat?.init();
        });
      } else {
        (window as any).greetoChat.init();
      }
    } else {
      console.error('[Greeto Chat] No data-api-key attribute found on script tag');
    }
  }
}

export default GreetoChatWidget;
