// Code Generated by Sidekick is for learning and experimentation purposes only.

// src/main.tsx - Development mode with API config fetch

import React from 'react';
import ReactDOM from 'react-dom/client';
import ChatWidget from './components/ChatWidget';
import './index.css';
import { setApiKey } from './config/api';
import apiClient from './config/api';

console.log('[Greeto Chat DEV] Running in development mode');
console.log('[Greeto Chat DEV] API URL:', import.meta.env.VITE_API_BASE_URL);

// ✅ Get API key (priority: script tag > .env)
const getApiKey = (): string | null => {
  // Check for script tag with data-api-key
  const scriptTag = document.querySelector('script[data-api-key]') as HTMLScriptElement;
  if (scriptTag) {
    const apiKey = scriptTag.getAttribute('data-api-key');
    if (apiKey) {
      console.log('[Greeto Chat DEV] Using API key from script tag');
      return apiKey;
    }
  }
  
  // Fallback to .env
  const envApiKey = import.meta.env.VITE_DEV_API_KEY;
  if (envApiKey) {
    console.log('[Greeto Chat DEV] Using API key from .env');
    return envApiKey;
  }
  
  console.error('[Greeto Chat DEV] No API key found!');
  return null;
};

// ✅ Fetch widget config from backend
const fetchWidgetConfig = async (apiKey: string) => {
  try {
    console.log('[Greeto Chat DEV] Fetching widget config...');
    const { data } = await apiClient.get('/widget/config', {
      headers: { 'X-API-Key': apiKey }
    });
    
    console.log('[Greeto Chat DEV] Config fetched:', data);
    return data;
  } catch (error: any) {
    console.error('[Greeto Chat DEV] Failed to fetch config:', error.message);
    // Return default config
    return {
      success: true,
      client_name: 'Default Client',
      widget_config: {
        primaryColor: '#2563EB',
        secondaryColor: '#1d4ed8',
        position: 'bottom-right',
        welcomeMessage: 'Hi! How can I help you today?'
      }
    };
  }
};

// ✅ Apply widget config to CSS variables and container
const applyWidgetConfig = (config: any, container: HTMLElement) => {
  const widgetConfig = config.widget_config;
  
  // Set CSS variables for dynamic theming
  container.style.setProperty('--color-theme-primary', widgetConfig.primaryColor);
  container.style.setProperty('--color-theme-secondary', widgetConfig.secondaryColor);
  container.style.setProperty('--color-theme-primary-hover', widgetConfig.secondaryColor);
  
  // Lighter shade for focus rings (calculate from primary color)
  const primaryRgb = hexToRgb(widgetConfig.primaryColor);
  const lightColor = primaryRgb 
    ? `rgba(${primaryRgb.r}, ${primaryRgb.g}, ${primaryRgb.b}, 0.2)` 
    : '#dbeafe';
  container.style.setProperty('--color-theme-primary-light', lightColor);
  
  // Store position and welcome message as data attributes
  container.setAttribute('data-position', widgetConfig.position);
  container.setAttribute('data-welcome-message', widgetConfig.welcomeMessage);
  
  console.log('[Greeto Chat DEV] Config applied successfully');
};

// ✅ Helper: Convert hex to RGB
const hexToRgb = (hex: string): { r: number; g: number; b: number } | null => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : null;
};

// ✅ Initialize widget
const initWidget = async () => {
  const apiKey = getApiKey();
  
  if (!apiKey) {
    console.error('[Greeto Chat DEV] Cannot initialize widget without API key');
    return;
  }
  
  // Set API key globally
  setApiKey(apiKey);
  
  // Create widget container
  const widgetContainer = document.createElement('div');
  widgetContainer.id = 'greeto-chat-widget-container';
  document.body.appendChild(widgetContainer);
  
  // Fetch config from backend
  const config = await fetchWidgetConfig(apiKey);
  
  // Apply config to container
  applyWidgetConfig(config, widgetContainer);
  
  // Render widget
  ReactDOM.createRoot(widgetContainer).render(
    <React.StrictMode>
      <ChatWidget />
    </React.StrictMode>
  );
};

// ✅ Start when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initWidget);
} else {
  initWidget();
}
