// Code Generated by Sidekick is for learning and experimentation purposes only.
// src/widget.tsx

import React from 'react';
import ChatWidget from './components/ChatWidget';
import './index.css';

/**
 * Main Widget Component
 * No props needed - reads configuration from CSS variables set by embed.ts
 */
const Widget = () => {
  return (
    <React.StrictMode>
      <ChatWidget />
    </React.StrictMode>
  );
};

export default Widget;
